// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY-bGslVnweLP0xdS9CSmJX4koU1vzaYQ',
    appId: '1:617047736305:web:5fbeefe3b425032a0f4e50',
    messagingSenderId: '617047736305',
    projectId: 'event-scout-288c9',
    authDomain: 'event-scout-288c9.firebaseapp.com',
    storageBucket: 'event-scout-288c9.appspot.com',
    measurementId: 'G-PZJESV6F33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKNgW2kapbBQslas4nDnYw03xe-Ktjjqo',
    appId: '1:617047736305:android:35f741b946fdbaea0f4e50',
    messagingSenderId: '617047736305',
    projectId: 'event-scout-288c9',
    storageBucket: 'event-scout-288c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2ErRS5kzd_d5VKJ34ETsgmAPHtm914Jc',
    appId: '1:617047736305:ios:82820bf39337aad60f4e50',
    messagingSenderId: '617047736305',
    projectId: 'event-scout-288c9',
    storageBucket: 'event-scout-288c9.appspot.com',
    iosBundleId: 'com.example.mShare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2ErRS5kzd_d5VKJ34ETsgmAPHtm914Jc',
    appId: '1:617047736305:ios:82820bf39337aad60f4e50',
    messagingSenderId: '617047736305',
    projectId: 'event-scout-288c9',
    storageBucket: 'event-scout-288c9.appspot.com',
    iosBundleId: 'com.example.mShare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY-bGslVnweLP0xdS9CSmJX4koU1vzaYQ',
    appId: '1:617047736305:web:f3e4a180a65915020f4e50',
    messagingSenderId: '617047736305',
    projectId: 'event-scout-288c9',
    authDomain: 'event-scout-288c9.firebaseapp.com',
    storageBucket: 'event-scout-288c9.appspot.com',
    measurementId: 'G-41LZ20WRJ9',
  );
}
